#!/bin/python3
#Spencer "Spinjrock" Oswald Oct 2023
#This is the script that pairs with the audispd plugin. It logs any traffic tagged INET, which is all socket creations with
#a0=2 or 10 and prints their pid lineage back to 1 to a log file defined with the variable log_path

import sys
import audit
import auparse
import os
import logging
import typing
from dataclasses import dataclass

LOG_FILE="/var/log/audit/kn1gh7.log"
APPEND_PERMISSIONS="a"

#Logging setup, TODO: Drop the level from debug in the end
logging.basicConfig(
        filename = LOG_FILE,
        encoding = 'utf-8',
        level=logging.DEBUG,
        format='%(asctime)s > %(levelname)s:%(message)s',
        datefmt='%m/%d/%Y>%I:%M:%S%p'
        )

@dataclass
class Process:
    """A little class to hold process data"""
    pid: int
    ppid: int
    cmd: str
    tty: str
    def __init__(self, id: int) -> None:
        """Initalizes from a PID"""
        self.pid = id
        ppid = os.popen("ps -o ppid --no-headers %i" % id).read().strip()
        self.ppid = int(ppid) if ppid != '' else 0
        self.cmd = os.popen("ps -o cmd --no-headers %i" % id).read().strip()
        self.tty = os.popen("ps -o tty --no-headers %i" % id).read().strip()

def lineage(p: Process) -> list[Process]:
    logging.info("Lineage: Checking in on process: "+str(p))
    if p.ppid == 1 or 0:
        return [Process]
    parent_process = Process(p.ppid)
    trace = [Process]
    trace += lineage(parent_process)
    return trace

def is_tagged_inet(line:str) -> bool:
    logging.info("is_tagged_inet checking")
    aup = auparse.AuParser(auparse.AUSOURCE_BUFFER, line)
    logging.info("aup_initailizing")
    if not aup:
        logging.critical("is_tagged_inet: Error initalizing AuParse")
        sys.exit(1)
    while aup.parse_next_event():
        logging.warning("Lets find the loop")
        while aup.get_field_name() != "key" && aup.next_field() != False:
        if aup.get_field_name() == "key":
            logging.info(aup.get_field_string())
        

if __name__ == '__main__':
    try:
        logging.info("Starting up...")
        for line in sys.stdin:
            logging.info("Reading Line")
            is_tagged_inet(line)
    except Exception as err:
        logging.critical(err)

sys.exit(0)
