#!/bin/bash
#A quick script to remove the programs if needed

rm -v /usr/bin/kn1gh7
rm -v /etc/audit/rules.d/kn1gh7.rules
rm -v /etc/audit/plugins.d/kn1gh7.conf
rm -v /var/log/audit/kn1gh7.log
service auditd restart
